server:
  port: 8082
spring:
  graphql:
    graphiql:
      enabled: true
      path: /playground
    path: /
    schema:
      introspection:
        enabled: true
      printer:
        enabled: true
    websocket:
      path: /subscription
